import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Logout",
  description: "Facebook Generated by create next app",
};

export default function AddminLayout({ children }) {
  return (
    <>
    <span>Adminlogout Navbar</span>
        {children}
     </>
  );
}
